[package]
name = "alpaca_display"
version = "0.1.0"
edition = "2021"

[dependencies]
# Library for interfacing with Waveshare e-ink displays
epd-waveshare = "0.5.0"

# General-purpose 2D graphics library
embedded-graphics = "0.8.0"

# GPIO/SPI control library for Raspberry Pi
rppal = "0.14.0"

